name: First

on:
  workflow_dispatch:

jobs:
  dummy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Print Hello World
        run: echo "Hello, World!"
